const ADD_TO_CART = 'cart_item/ADDED_TO_CART';
const REMOVE_FROM_CART = 'cart_item/REMOVE_FROM_CART';
const INCREASE_COUNT_ITEM_CART = 'cart_item/INCREASE_COUNT_ITEM_CART';
const DECREASE_COUNT_ITEM_CART = 'cart_item/DECREASE_COUNT_ITEM_CART';

export default {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  INCREASE_COUNT_ITEM_CART,
  DECREASE_COUNT_ITEM_CART,
};
