const FETCH_REQUEST_START = 'FETCH_REQUEST_START';
const FETCH_REQUEST_SUCCESS = 'FETHC_REQUEST_SUCCESS';
const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
const FETCH_REQUEST_MENU = 'menu_items/FETCH_REQUEST_MENU';
const FETCH_REQUEST_MENU__BY_CATEGORY = 'menu_items_category/FETCH_REQUEST';
const FETCH_REQUEST_CATEGORIES = 'menu_categoties/FETCH_REQUEST_CATEGORIES';
const CHANGE_FILTER = 'menu/CHANGE_FILTER';
const CHANGE_SEARCH_FILTER = 'menu/CHANGE_SEARCH_FILTER';
const RESET_FILTER = 'menu/RESET_FILTER';
const DELETE_ITEM = 'menu_item/DELETE_ITEM';
const OPEN_MODAL_FLAG = 'modal_window/TOOGLE';
const UPDATE_MENU_ITEM = 'menu_item_update/UPDATE_ITEM';

export default {
  FETCH_REQUEST_START,
  FETCH_REQUEST_SUCCESS,
  FETCH_REQUEST_ERROR,
  FETCH_REQUEST_MENU,
  FETCH_REQUEST_MENU__BY_CATEGORY,
  FETCH_REQUEST_CATEGORIES,
  CHANGE_FILTER,
  CHANGE_SEARCH_FILTER,
  RESET_FILTER,
  DELETE_ITEM,
  OPEN_MODAL_FLAG,
  UPDATE_MENU_ITEM,
};
